import XCTest
@testable import EscapePhone

@MainActor
final class ExpandedPuzzleTests: XCTestCase {
    private func makeApp(store: InMemoryGameProgressStore = InMemoryGameProgressStore()) -> AppContainer { AppContainer(store: store, motion: MockMotionController(), haptics: NoOpHapticProvider(), ads: NoOpAdGateway(), device: NoOpPuzzleDeviceConnector(), dateProvider: FixedDateProvider(now: Date(timeIntervalSince1970: 1_700_000_000))) }
    func test_completeEncryptedNotePuzzle_unlocksAudioRecord() { let app = makeApp(); app.completeEncryptedNotePuzzle(); XCTAssertTrue(app.gameProgress.encryptedNoteSolved); XCTAssertTrue(app.canOpen(.audioRecordPuzzle)) }
    func test_submitAudioOrder_withCorrectOrder_succeeds() { var engine = AudioRecordPuzzleEngine(fragments: AudioRecordPuzzleEngine.fragments); XCTAssertTrue(engine.submitAudioOrder()) }
    func test_submitAudioOrder_withWrongOrder_fails() { var engine = AudioRecordPuzzleEngine(fragments: AudioRecordPuzzleEngine.fragments.reversed()); XCTAssertFalse(engine.submitAudioOrder()) }
    func test_validateCommitGraph_withCorrectGraph_succeeds() { var engine = CommitGraphPuzzleEngine(); for (index, node) in engine.nodes.sorted(by: { $0.correctOrder < $1.correctOrder }).enumerated() { engine.moveCommitNode(node.id, branch: node.correctBranch); engine.moveCommitNode(node.id, newIndex: index) }; engine.connectCommitNode("417", toId: "418"); engine.connectCommitNode("418", toId: "420"); XCTAssertTrue(engine.validateCommitGraph()) }
    func test_validateCommitGraph_withWrongBranch_fails() { var engine = CommitGraphPuzzleEngine(); for (index, node) in engine.nodes.sorted(by: { $0.correctOrder < $1.correctOrder }).enumerated() { engine.moveCommitNode(node.id, branch: node.id == "417" ? "hotfix" : node.correctBranch); engine.moveCommitNode(node.id, newIndex: index) }; engine.connectCommitNode("417", toId: "418"); engine.connectCommitNode("418", toId: "420"); XCTAssertFalse(engine.validateCommitGraph()) }
    func test_validateAccessLogAnswers_withCorrectAnswers_succeeds() { var engine = AccessLogPuzzleEngine(); for (index, answer) in engine.correctAnswers.enumerated() { engine.answerLogQuestion(index, answer: answer) }; XCTAssertTrue(engine.validateAccessLogAnswers()) }
    func test_selectPublicDisclosure_savesEndingType() { let store = InMemoryGameProgressStore(); let app = makeApp(store: store); app.selectPublicDisclosure(); XCTAssertEqual(store.gameProgress?.endingType, .publicDisclosure) }
    func test_selectEncryptedArchive_savesEndingType() { let store = InMemoryGameProgressStore(); let app = makeApp(store: store); app.selectEncryptedArchive(); XCTAssertEqual(store.gameProgress?.endingType, .encryptedArchive) }
    func test_loadLegacyProgress_appliesNewDefaultValues() throws { let legacy = #"{"currentStage":"flashlightSolved","messengerSolved":true,"flashlightSolved":true,"discoveredDigits":[4,1,7]}"#.data(using: .utf8)!; let progress = try JSONDecoder().decode(GameProgress.self, from: legacy); XCTAssertFalse(progress.encryptedNoteSolved); XCTAssertFalse(progress.audioRecordSolved); XCTAssertFalse(progress.commitGraphSolved); XCTAssertFalse(progress.accessLogSolved); XCTAssertNil(progress.endingType); XCTAssertTrue(progress.collectedEvidenceIds.isEmpty); XCTAssertTrue(progress.puzzleAnalytics.isEmpty); XCTAssertNil(progress.playerFeedback); XCTAssertTrue(progress.playtestHistory.isEmpty); XCTAssertEqual(progress.analyticsConsentStatus, .notDetermined); XCTAssertTrue(progress.pendingAnalyticsUploads.isEmpty); XCTAssertNil(progress.lastAnalyticsUploadAt); XCTAssertNil(progress.lastAnalyticsUploadError) }
}
